### ISSUE TITLE
enhorabuena + propuesta de mejora

### ISSUE THREAD

**Issue by joselet** [geowe/openCrogis#1]
Hola Geowe.

Antes que nada, enhorabuena por tan buena iniciativa y por compartirlo con la comunidad. Soy José Manuel, ando tras una solución similar, de hecho intentando programar una propia hasta que he tropezado con vosotros. Fantástico proyecto!

Me gustaría saber si tenéis pensado o si necesitais colaboración para que los croquis puedan ser salvados y recuperados.
Veo que esa característica está disponible para salvar el croquis en formato .json

¿Tenéis pensado que tambien se puedan cargar croquis? seguro que sí.
¿Tenéis pensado que se pueda salvar/cargar desde una conexión de BD PostgreSQL/Postgis?

Muchas gracias y adelante con ello. Aquí tenéis un humilde seguidor

**Comment by i62lotor** [comment]
Hola, José Manuel
gracias por tu comentario.

En la versión actual, se puede guardar el croquis a un fichero (en formato json), donde se guarda la fecha y el GeoJson de cada una de las capas implicadas en el croquis (me gusta llamarlo crogis, ya que es un croquis georeferenciado :o) ).

Para cargar el croquis, se puede hacer a través de una parámetro en la url. Es decir, si el croquis está accesible vía url, se puede cargar usando el parámetro **url** en la petición. Por ejemplo:
```http://geowe.org/openCrogis/?url=https://raw.githubusercontent.com/i62lotor/geodata/master/crogis/open-croquis.json```

Te dejo el enlace de la documentación: [Guardar y cargar croquis](https://geowe.org/openCrogis/doc/es/guardar-cargar.html)

Respecto a guardar/cargar desde una BD, en principio no está contemplado implementarlo en este proyecto, pero si que lo hemos implementado en otro sistema. Haría falta un mecanismo de acceso a las base de datos, por ejemplo con un servicio web (tipo Rest, por ejemplo), que ofreciera el .json. Con ese servicio se podría usar openCrogis, para cargar, sin tener que cambiar el código.

Si te animas a implementar cualquier funcionalidad y compartirla, estaremos encantados de recibir tus PR.

Un saludo
